version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: collab_board_db
    restart: always
    environment:
      POSTGRES_USER: aniket
      POSTGRES_PASSWORD: sapra
      POSTGRES_DB: collab_board
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
